City to city
raerpo/huemul-airlines pull request #4
Opened 2019-05-28 21:51 UTC by levelasquez

Se agrego la opción de poder elegir la ciudad de origin y se incorporo el valor en dólares.

2019-06-04 16:05 UTC, raerpo requested changes

2019-06-04 16:05 UTC, raerpo commented on index.js
> +          const { data: dolarToday } = await axios.get('https://mindicador.cl/api/dolar')
I'm not so convinced about depending on another API to give a response. If `minindicador` fails we won't show the response that we got from despegar. 

I think we have to ways here. Adding an optional query parameter to enable the USD conversion or making sure that if you get an exception from minindicator this won't break the response.

Also, another option is making the request to despegar in panama so you will be able to see prices in USD dollars and you can buy them through that site too `https://www.despegar.com.pa/vuelos/scl/bog/`

2019-06-04 16:05 UTC, raerpo commented on cities.js
> +  cucuta: 'cuc',
This file is no longer needed with the inclusion of `utils.findCities`

2019-06-04 16:05 UTC, raerpo commented
Thanks for your contributions! Really appreciate them

2025-04-23 21:31 UTC, levelasquez commented
close due to inactivity :)

2025-04-23 21:31 UTC, closed without merging